language: java
jdk: 
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
script: 
  - gradle build
notifications:
  email:
    recipients:
      - d3psigames@gmail.com
      - pluscrafter123@hotmail.com
    on_success: always
    on_failure: always
