language: java
jdk:
  - oraclejdk9
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install gradle 6.0
script: 
  - gradle build
notifications:
  email:
    recipients:
      - d3psigames@gmail.com
      - pluscrafter123@hotmail.com
    on_success: always
    on_failure: always
    
